import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{site}from'./content';
import'./styles.css';

const Icon=({children})=><span aria-hidden="true" style={{fontSize:16}}>{children}</span>;
const Menu=()=> <Icon>☰</Icon>, X=()=> <Icon>×</Icon>, ArrowDownRight=()=> <Icon>↘</Icon>, MapPin=()=> <Icon>⌖</Icon>, ArrowUpRight=()=> <Icon>↗</Icon>;

const NAV=[['01','The Cover','cover'],['02','The Invitation','invitation'],['03','The Program','program'],['04','Before All This','story'],['05','New York, According to Us','new-york'],['06','Getting Here','travel'],['07','What to Wear','attire'],['08','Questions, Answered','questions'],['09','RSVP','rsvp'],['10','Gifts','gifts'],['11','Get in Touch','contact']];
const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
function Label({n,children}){return <div className="folio"><span>{n}</span>{children}</div>}
function Button({children,onClick,light=false}){return <button className={'btn '+(light?'light':'')} onClick={onClick}>{children}<ArrowUpRight size={14}/></button>}
function Seal(){return <div className="seal"><span>PROPERTY OF</span><b>SK+KS</b><small>NYC</small></div>}
function Skyline(){return <svg className="hero-art" viewBox="0 0 900 630" role="img" aria-label="Two formally dressed figures approach the New York Athletic Club as guests quietly prepare along Central Park South."><g className="wash"><path d="M0 470Q130 370 280 438t250-7q150-90 370 4v195H0z"/><path d="M0 90h260v350H0z"/></g><g className="ink"><path d="M420 76h380v450H420zM455 120h310M470 160v366M525 160v366M580 160v366M635 160v366M690 160v366M745 160v366M590 430q25-28 50 0v96M410 526h410M0 470h900"/><path d="M35 428h210l35 68H20zM70 400h135l38 28H35z"/><circle cx="88" cy="496" r="20"/><circle cx="228" cy="496" r="20"/><path d="M130 432v-26m0 0 10-10m-10 10-10-10M326 410q-9 28-5 110m8-82 28 78m-38-48-21 49M370 404q18 46 9 116m-5-70-28 65m31-52 25 54"/><circle cx="327" cy="395" r="13"/><circle cx="369" cy="389" r="13"/><path d="M840 461q-17 10-4 30h28q12-18-6-30m-12-4v-20m-14 7h28"/></g><text x="455" y="110" className="building-label">NEW YORK ATHLETIC CLUB</text><text x="78" y="423" className="tiny">JUNE 5</text><circle className="taxi-light" cx="157" cy="398" r="5"/></svg>}
function Spot({type}){const art={early:'5:17',tissues:'···',glasses:'◡ ◡',dance:'↗ ↘',shoe:'⌒',mail:'S. & K.\nN.Y.C.',key:'JUNE 5',coffee:'COFFEE',ticket:'SK+KS'};return <div className={'spot '+type} aria-hidden="true"><span>{art[type]||'✦'}</span></div>}
function Header(){const[open,setOpen]=useState(false);return <><header><button className="brand" onClick={()=>scroll('cover')}>S + K <small>JUNE 05 · NYC</small></button><nav aria-label="Main navigation">{NAV.slice(0,3).map(x=><button key={x[0]} onClick={()=>scroll(x[2])}><i>{x[0]}</i>{x[1]}</button>)}</nav><button className="rsvp-top" onClick={()=>scroll('rsvp')}>RSVP</button><button className="menu" aria-expanded={open} aria-label="Open menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="drawer">{NAV.map(x=><button key={x[0]} onClick={()=>{scroll(x[2]);setOpen(false)}}><span>{x[0]}</span>{x[1]}</button>)}</div>}</>}
function Actions(){const[msg,setMsg]=useState('');const cal=()=>{const data=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:20270605T213000Z\nDTEND:20270606T040000Z\nSUMMARY:Sophie & Ken’s Wedding\nLOCATION:${site.venue.address}, ${site.venue.city}\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/calendar'}));a.download='sophie-and-ken.ics';a.click();setMsg('Your calendar is now involved.');};return <div><div className="actions"><Button onClick={()=>scroll('rsvp')}>RSVP</Button><Button onClick={cal}>Add to calendar</Button><Button onClick={()=>navigator.clipboard.writeText(`${site.venue.address}, ${site.venue.city}`).then(()=>setMsg('Copied. One less thing to remember.'))}>Copy address</Button><a className="btn" href={site.venue.maps} target="_blank">Open in maps <MapPin size={14}/></a></div><div className="toast" aria-live="polite">{msg}</div></div>}
function Cover(){return <section id="cover" className="cover"><div className="cover-copy"><Label n="01">Saturday edition</Label><h1><span>Sophie</span><small>Knochenhauer</small><em>&</em><span>Ken</span><small>Syme</small></h1><div className="aside"><p>We’re getting married.</p><p>Apparently, it requires a website.</p></div><div className="date"><b>SATURDAY, JUNE 5, 2027</b><span>NEW YORK ATHLETIC CLUB</span><span>NEW YORK, NEW YORK</span></div><div className="actions"><Button onClick={()=>scroll('rsvp')}>RSVP</Button><button className="text-btn" onClick={()=>scroll('details')}>THE DETAILS <ArrowDownRight/></button></div></div><div className="art-wrap"><Skyline/><div className="stamp">CENTRAL PARK SOUTH</div></div><div className="edition">ISSUED TO<br/>FRIENDS & FAMILY</div></section>}
function Invitation(){return <><section id="details" className="details"><div><Label n="—">At a glance</Label><h2>The Details</h2><p className="dek">The important details are below. The unimportant ones are mostly there too.</p></div><div className="details-card"><time>SATURDAY<br/>JUNE 5, 2027</time><p><b>{site.venue.name}</b><br/>{site.venue.address}<br/>{site.venue.city}</p><Actions/></div></section><section id="invitation" className="invitation"><Spot type="mail"/><Label n="02">The Invitation</Label><div className="invite-inner"><p className="names">SOPHIE KNOCHENHAUER <i>AND</i> KEN SYME</p><h2>Please join us.</h2><p>Sophie Knochenhauer and Ken Syme request the pleasure of your company at their wedding.</p><p>There will be a ceremony, cocktails, dinner, dancing and, eventually, an after-party.</p><div className="invite-meta"><b>SATURDAY, JUNE 5, 2027</b><span>NEW YORK ATHLETIC CLUB</span><span>180 CENTRAL PARK SOUTH · NEW YORK, NEW YORK</span></div><Actions/></div><Seal/></section></>}
function Program(){return <><section id="program" className="section program"><Label n="03">The Program</Label><div className="section-head"><h2>The Program</h2><p>One evening, four acts. All of it at 180 Central Park South.</p></div><div className="program-list">{site.program.map((p,i)=><article key={p[0]}><div className="act">ACT {['I','II','III','IV','V'][i]}</div><time>{p[1]}</time><div><h3>{p[0]}</h3><p>{p[2]}</p>{i===4&&<small>More information will follow. For now, assume the evening continues.</small>}</div><Spot type={p[3]}/></article>)}</div></section><section className="night"><div><p>A short walk from the park.</p><h2>A long way from an early night.</h2><small>NEW YORK ATHLETIC CLUB<br/>180 CENTRAL PARK SOUTH</small><a className="btn light" href={site.venue.maps}>Get directions <ArrowUpRight size={14}/></a></div><div className="night-art"><span>JUNE 5</span></div></section></>}
function FeatureSections(){return <><section id="story" className="section story"><Label n="04">Before All This</Label><div className="section-head"><h2>Before All This</h2><p>There are several versions of how this started. This is the one we agreed to publish.</p></div><div className="placeholder"><b>THE BEGINNING</b><p>Their story will appear here when Sophie and Ken have agreed on the facts.</p><div className="memory"><div><small>ACCORDING TO SOPHIE</small><div className="restaurant">An effortless evening.</div></div><div><small>ACCORDING TO KEN</small><div className="restaurant worried">Calm. Cool.<br/>Do not order the steak.</div></div></div><caption>Same night. Two completely different memories.</caption></div><p className="closing">The story is still in progress. This part has a dress code.</p></section><section id="new-york" className="section guide"><Label n="05">New York, According to Us</Label><div className="section-head"><h2>New York,<br/><i>According to Us</i></h2><p>You cannot do New York in a weekend. This has never stopped anyone from trying.</p><p>These are the places we would send you when left in charge of your limited time, appetite and judgment.</p></div><div className="plan"><div className="map-lines">↗︎ ↓ ↙︎ → ↗︎</div><ol><li>8:00 — Breakfast downtown</li><li>9:30 — Museum uptown</li><li>12:00 — Lunch in Brooklyn</li><li>2:00 — Walk the High Line</li><li>4:00 — Drinks downtown</li><li>5:30 — Wedding</li><li><s>5:15 — “Quick nap”</s></li></ol><caption>A perfectly reasonable Saturday, on paper.</caption></div><div className="guide-grid">{site.guide.map(x=><article key={x[0]}><span>UNDER REVIEW</span><h3>{x[0]}</h3><p>{x[1]}</p><small>Recommendations forthcoming.</small></article>)}</div></section></>}
function TravelAttire(){return <><section id="travel" className="section travel"><Label n="06">Getting Here</Label><div className="section-head"><h2>Getting Here.<br/>Staying Here.</h2><p>New York has three airports, several train stations and an impressive number of ways to take the wrong route. These are the simplest options.</p></div><div className="travel-grid"><article><h3>By plane</h3><p>Fly into whichever airport produces the least offensive combination of price and arrival time.</p></article><article><h3>By train</h3><p>Penn Station and Grand Central are both convenient, depending on where you are coming from and how strongly you feel about train stations.</p></article><article><h3>By car</h3><p>If you are brave enough to drive into Manhattan, valet parking is available at the venue.</p></article><article><h3>Getting around</h3><p>The venue is on Central Park South and is easy to reach by subway, cab or a walk in shoes you have planned appropriately.</p></article></div><div className="cab"><div className="luggage">BLACK TIE<br/><b>KEEP<br/>UPRIGHT</b></div><caption>Travel light. Or travel correctly.</caption></div><div className="hotel"><Spot type="key"/><h3>A Few Places to Sleep</h3><p>We have identified several respectable places to recover. What time you actually return to them is up to you.</p><small>Hotel recommendations and confirmed room blocks will appear here.</small></div></section><section id="attire" className="section attire"><Label n="07">What to Wear</Label><div className="attire-copy"><h2>Black Tie<br/><i>Optional</i></h2><h3>Dress for a very good night.</h3><p>Tuxedos, dark suits, gowns and formal dresses are all appropriate.</p><p>Wear the version of black tie in which you feel most like yourself. The goal is polished, not identical.</p><b>Dress for the room. Prepare for the sidewalk.</b></div><div className="crosswalk" role="img" aria-label="Impeccably dressed guests wait at a Manhattan crosswalk, with practical footwear below their formal clothes.">{[1,2,3,4,5].map(n=><i key={n}></i>)}</div></section></>}
function Questions(){return <section id="questions" className="section questions"><Label n="08">Questions, Answered</Label><div className="section-head"><h2>Everything You<br/>Were About to Ask</h2><p>We tried to answer it before it became a text. Though if you have questions, feel free to text.</p></div><div className="suitcase"><span>CEREMONY</span><span>WEATHER</span><span>AFTER-PARTY</span><span>EMERGENCY OUTFIT #1</span><span>QUESTIONS FOR KEN</span><caption>Most of this is answered below.</caption></div><div className="accordions">{site.faq.map((x,i)=><details key={x[0]} open={i===0}><summary><span>{String(i+1).padStart(2,'0')}</span>{x[0]}</summary><p>{x[1]}</p></details>)}</div></section>}
function RSVP(){const[step,setStep]=useState(0),[name,setName]=useState(''),[loading,setLoading]=useState(false);const lookup=e=>{e.preventDefault();setLoading(true);setTimeout(()=>{setLoading(false);setStep(1)},700)};return <section id="rsvp" className="section rsvp"><Label n="09">RSVP</Label><div className="rsvp-art"><div className="list">GUEST LIST<br/>——————<br/>——————<br/>——————<br/>——————<br/>——————</div><div className="wave">S + K<br/>⌁</div></div><div className="rsvp-box">{step===0?<><h2>Let’s Find Your Invitation</h2><p>Enter your name exactly as it appears on the invitation.</p><p>We promise this is less ominous than it sounds.</p><form onSubmit={lookup}><label>FIRST AND LAST NAME<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><button className="btn" disabled={loading}>{loading?'Checking the list…':'Find my invitation'} <ArrowUpRight size={14}/></button></form></>:<><h2>We couldn’t find that name.</h2><p>Check the spelling, try another member of your household or contact us and we’ll sort it out.</p><p className="privacy">The production guest list is private and has not yet been connected to this preview.</p><Button onClick={()=>setStep(0)}>Try again</Button></>}</div></section>}
function End(){return <><section id="gifts" className="section gifts"><Label n="10">Gifts</Label><div><h2>There Is, Apparently,<br/>Also a Registry</h2><p>Having you with us is the point.</p><p>For those who have asked anyway, we have put a few ideas here.</p><small>Registry details forthcoming.</small></div><div className="gift">?</div></section><section id="contact" className="section contact"><Label n="11">Get in Touch</Label><h2>One More Question?</h2><p>We may have missed something. It happens rarely, but not never.</p><p>Confirmed contact details will appear here.</p></section><footer><div><b>SOPHIE + KEN</b><span>JUNE 5, 2027</span><span>NEW YORK, NEW YORK</span></div><Seal/><p>PROPERTY OF SK+KS. NYC.</p><small>Made for June 5, 2027. After that, archival material.</small></footer></>}
function App(){return <><Header/><main><Cover/><Invitation/><Program/><FeatureSections/><TravelAttire/><Questions/><RSVP/><End/></main></>};
createRoot(document.getElementById('root')).render(<App/>);
